# Generated by Django 5.1.1 on 2024-09-17 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_feelings_moodentry_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoodEntry',
            new_name='Product',
        ),
    ]
