# Generated by Django 5.1.1 on 2024-11-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_moodentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
